# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: coopdeluxe.sm64coopdx
PackageVersion: 1.0.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: sm64coopdx.exe
InstallModes:
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2024-09-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/coop-deluxe/sm64coopdx/releases/download/v1.0.3/sm64coopdx_v1.0.3_Windows_OpenGL.zip
  InstallerSha256: 5F2FB6F673CA2E001027E46BE48FDF91BFABDF6F5EFE907AB08B503048C525F4
ManifestType: installer
ManifestVersion: 1.6.0
